# Simple package

name: shortcuts
parent: default

global_vars:
  - name: "timestamp"
    type: "date"
    params:
      format: "%s"
  - name: "date"
    type: "date"
    params:
      format: "%Y-%m-%d"

matches:
  # Date and marks
  - trigger: ":now"
    replace: "{{timestamp}}"

  - trigger: ":date"
    replace: "{{date}}"

  # Mac Icons
  - trigger: ":cmd"
    replace: "⌘"

  - trigger: ":shift"
    replace: "⇧"

  - trigger: ":opt"
    replace: "⌥"

  - trigger: ":ctrl"
    replace: "⌃"

  # emojis
  - trigger: ":sparkles"
    replace: "✨"

  - trigger: ":tada"
    replace: "🎉"

  - trigger: ":ok"
    replace: "✅"

  - trigger: ":ko"
    replace: "🙅‍♀️"

  # curled
  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl -s 'https://api.ipify.org'"

- trigger: :mit-long
  replace: "{{output}}"
  vars:
  - name: output
    type: shell
    params:
      cmd: "curl -s 'https://gist.githubusercontent.com/Lissy93/143d2ee01ccc5c052a17/raw/a8ac96cd15847a231931b561d95d2de47066fd33/LICENSE.MD'"